# config/routes.yaml

# the "app_home" route name is not important yet
index:
    path: /
    controller: App\Controller\PagesController::home


# the "app_pagebutton" route name is not important yet
pagebutton:
    path: /pagebutton
    controller: App\Controller\PagesController::pagebutton


# the "app_about" route name is not important yet
about:
    path: /about
    controller: App\Controller\PagesController::about


# the "app_articleletter" route name is not important yet
articleletter:
    path: /articleletter
    controller: App\Controller\PagesController::articleletter

# the "app_articlenumber" route name is not important yet
articlenumber:
    path: /articlenumber
    controller: App\Controller\PagesController::articlenumber


# the "app_numberform" route name is not important yet
numberform:
    path: /numberform
    controller: App\Controller\PagesController::numberform


# the "app_letterform" route name is not important yet
letterform:
    path: /letterform
    controller: App\Controller\PagesController::letterform


# the "app_genreform" route name is not important yet
genreform:
    path: /genreform
    controller: App\Controller\PagesController::genreform


# the "app_listlinkgenre" route name is not important yet
listlinkgenre:
    path: /listlinkgenre
    controller: App\Controller\PagesController::listlinkgenre


# the "app_articlegenre" route name is not important yet
articlegenre:
    path: /articlegenre
    controller: App\Controller\PagesController::articlegenre