# config/routes.yaml

# the "app_lucky_number" route name is not important yet
index:
    path: /
    controller: App\Controller\PagesController::home


# the "app_lucky_number" route name is not important yet
article:
    path: /article
    controller: App\Controller\ArticleWikiController::article